In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import os

folder_path = "/content/drive/MyDrive/PN BPP"

print(os.listdir(folder_path))

['putusan_65_pid (1).b_2026_pn_bpp_20260623100320.pdf', 'putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf', 'putusan_66_pid (1).b_2026_pn_bpp_20260622200457.pdf', 'putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf', 'putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf', 'putusan_441_pid (1).b_2025_pn_bpp_20260624212232.pdf', 'putusan_441_pid.b_2025_pn_bpp_20260624212232.pdf', 'putusan_238_pid.b_2025_pn_bpp_20260624212310.pdf', 'putusan_48_pid (1).b_2025_pn_bpp_20260624212421.pdf', 'putusan_48_pid.b_2025_pn_bpp_20260624212421.pdf', 'putusan_288_pid.b_2024_pn_bpp_20260624212441.pdf', 'putusan_645_pid (1).b_2023_pn_bpp_20260624212459.pdf', 'putusan_645_pid.b_2023_pn_bpp_20260624212459.pdf', 'putusan_528_pid (1).b_2023_pn_bpp_20260624212514.pdf', 'putusan_528_pid.b_2023_pn_bpp_20260624212514.pdf', 'putusan_272_pid.b_2023_pn_bpp_20260624212529.pdf', 'putusan_283_pid (1).b_2023_pn_bpp_20260624212601.pdf', 'putusan_283_pid.b_2023_pn_bpp_20260624212601.pdf', 'putusan_300_pid.b_2023_pn_bpp_20260624212614.pdf', 'putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf', 'putusan_650_pid.b_2022_pn_bpp_20260624212656.pdf', 'putusan_641_pid.b_2022_pn_bpp_20260624212733.pdf', 'putusan_569_pid (1).b_2022_pn_bpp_20260624212745.pdf', 'putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf', 'putusan_552_pid (1).b_2022_pn_bpp_20260624212828.pdf', 'putusan_552_pid.b_2022_pn_bpp_20260624212828.pdf', 'putusan_555_pid.b_2022_pn_bpp_20260624212843.pdf', 'putusan_495_pid.b_2022_pn_bpp_20260624212853.pdf', 'putusan_546_pid (1).b_2022_pn_bpp_20260624212936.pdf', 'putusan_546_pid.b_2022_pn_bpp_20260624212936.pdf', 'putusan_571_pid.b_2022_pn_bpp_20260624212947.pdf', 'putusan_317_pid (1).b_2022_pn_bpp_20260624213009.pdf', 'putusan_317_pid.b_2022_pn_bpp_20260624213009.pdf', 'putusan_370_pid (1).b_2022_pn_bpp_20260624213044.pdf', 'putusan_370_pid.b_2022_pn_bpp_20260624213044.pdf', 'putusan_371_pid.b_2022_pn_bpp_20260624213126.pdf', 'putusan_20_pid (1).b_2022_pn_bpp_20260624213156.pdf', 'putusan_20_pid.b_2022_pn_bpp_20260624213156.pdf', 'putusan_499_pid.b_2021_pn_bpp_20260624213313.pdf', 'putusan_530_pid (1).b_2021_pn_bpp_20260624213349.pdf', 'putusan_530_pid.b_2021_pn_bpp_20260624213349.pdf', 'putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf', 'putusan_80_pid.b_2021_pn_bpp_20260624213521.pdf', 'putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf', 'cases.csv', 'cases_final.csv', 'PN BPP_final.csv', 'retrieval_result.csv', 'predictions.csv']

In [7]:
%cd /content/drive/MyDrive/PN BPP

/content/drive/MyDrive/PN BPP

In [8]:
!pwd

/content/drive/MyDrive/PN BPP

In [9]:
!ls "/content/drive/MyDrive/PN BPP"

 cases.csv
 cases_final.csv
'PN BPP_final.csv'
 predictions.csv
 putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf
'putusan_20_pid (1).b_2022_pn_bpp_20260624213156.pdf'
 putusan_20_pid.b_2022_pn_bpp_20260624213156.pdf
 putusan_238_pid.b_2025_pn_bpp_20260624212310.pdf
 putusan_272_pid.b_2023_pn_bpp_20260624212529.pdf
'putusan_283_pid (1).b_2023_pn_bpp_20260624212601.pdf'
 putusan_283_pid.b_2023_pn_bpp_20260624212601.pdf
 putusan_288_pid.b_2024_pn_bpp_20260624212441.pdf
 putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf
 putusan_300_pid.b_2023_pn_bpp_20260624212614.pdf
'putusan_317_pid (1).b_2022_pn_bpp_20260624213009.pdf'
 putusan_317_pid.b_2022_pn_bpp_20260624213009.pdf
'putusan_370_pid (1).b_2022_pn_bpp_20260624213044.pdf'
 putusan_370_pid.b_2022_pn_bpp_20260624213044.pdf
 putusan_371_pid.b_2022_pn_bpp_20260624213126.pdf
'putusan_441_pid (1).b_2025_pn_bpp_20260624212232.pdf'
 putusan_441_pid.b_2025_pn_bpp_20260624212232.pdf
'putusan_48_pid (1).b_2025_pn_bpp_20260624212421.pdf'
 putusan_48_pid.b_2025_pn_bpp_20260624212421.pdf
 putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf
 putusan_495_pid.b_2022_pn_bpp_20260624212853.pdf
 putusan_499_pid.b_2021_pn_bpp_20260624213313.pdf
'putusan_528_pid (1).b_2023_pn_bpp_20260624212514.pdf'
 putusan_528_pid.b_2023_pn_bpp_20260624212514.pdf
'putusan_530_pid (1).b_2021_pn_bpp_20260624213349.pdf'
 putusan_530_pid.b_2021_pn_bpp_20260624213349.pdf
'putusan_546_pid (1).b_2022_pn_bpp_20260624212936.pdf'
 putusan_546_pid.b_2022_pn_bpp_20260624212936.pdf
'putusan_552_pid (1).b_2022_pn_bpp_20260624212828.pdf'
 putusan_552_pid.b_2022_pn_bpp_20260624212828.pdf
 putusan_555_pid.b_2022_pn_bpp_20260624212843.pdf
'putusan_569_pid (1).b_2022_pn_bpp_20260624212745.pdf'
 putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf
 putusan_571_pid.b_2022_pn_bpp_20260624212947.pdf
 putusan_641_pid.b_2022_pn_bpp_20260624212733.pdf
'putusan_645_pid (1).b_2023_pn_bpp_20260624212459.pdf'
 putusan_645_pid.b_2023_pn_bpp_20260624212459.pdf
 putusan_650_pid.b_2022_pn_bpp_20260624212656.pdf
'putusan_65_pid (1).b_2026_pn_bpp_20260623100320.pdf'
 putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf
'putusan_66_pid (1).b_2026_pn_bpp_20260622200457.pdf'
 putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf
 putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf
 putusan_80_pid.b_2021_pn_bpp_20260624213521.pdf
 retrieval_result.csv

In [10]:
!find /content/drive/MyDrive -type d | grep "PN"

/content/drive/MyDrive/PN BPP

In [11]:
!pip install pypdf -q

import os
from pypdf import PdfReader

folder = "/content/drive/MyDrive/PN BPP"

cases = []

for file in os.listdir(folder):
    if file.endswith(".pdf"):
        path = os.path.join(folder, file)

        try:
            reader = PdfReader(path)

            text = ""
            for page in reader.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + " "

            cases.append({
                "filename": file,
                "text": text
            })

            print("Berhasil:", file)

        except Exception as e:
            print("Error:", file, e)

print("Jumlah dokumen:", len(cases))

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.5/349.5 kB 2.3 MB/s eta 0:00:00
Berhasil: putusan_65_pid (1).b_2026_pn_bpp_20260623100320.pdf
Berhasil: putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf
Berhasil: putusan_66_pid (1).b_2026_pn_bpp_20260622200457.pdf
Berhasil: putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf
Berhasil: putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf
Berhasil: putusan_441_pid (1).b_2025_pn_bpp_20260624212232.pdf
Berhasil: putusan_441_pid.b_2025_pn_bpp_20260624212232.pdf
Berhasil: putusan_238_pid.b_2025_pn_bpp_20260624212310.pdf
Berhasil: putusan_48_pid (1).b_2025_pn_bpp_20260624212421.pdf
Berhasil: putusan_48_pid.b_2025_pn_bpp_20260624212421.pdf
Berhasil: putusan_288_pid.b_2024_pn_bpp_20260624212441.pdf
Berhasil: putusan_645_pid (1).b_2023_pn_bpp_20260624212459.pdf
Berhasil: putusan_645_pid.b_2023_pn_bpp_20260624212459.pdf
Berhasil: putusan_528_pid (1).b_2023_pn_bpp_20260624212514.pdf
Berhasil: putusan_528_pid.b_2023_pn_bpp_20260624212514.pdf
Berhasil: putusan_272_pid.b_2023_pn_bpp_20260624212529.pdf
Berhasil: putusan_283_pid (1).b_2023_pn_bpp_20260624212601.pdf
Berhasil: putusan_283_pid.b_2023_pn_bpp_20260624212601.pdf
Berhasil: putusan_300_pid.b_2023_pn_bpp_20260624212614.pdf
Berhasil: putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf
Berhasil: putusan_650_pid.b_2022_pn_bpp_20260624212656.pdf
Berhasil: putusan_641_pid.b_2022_pn_bpp_20260624212733.pdf
Berhasil: putusan_569_pid (1).b_2022_pn_bpp_20260624212745.pdf
Berhasil: putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf
Berhasil: putusan_552_pid (1).b_2022_pn_bpp_20260624212828.pdf
Berhasil: putusan_552_pid.b_2022_pn_bpp_20260624212828.pdf
Berhasil: putusan_555_pid.b_2022_pn_bpp_20260624212843.pdf
Berhasil: putusan_495_pid.b_2022_pn_bpp_20260624212853.pdf
Berhasil: putusan_546_pid (1).b_2022_pn_bpp_20260624212936.pdf
Berhasil: putusan_546_pid.b_2022_pn_bpp_20260624212936.pdf
Berhasil: putusan_571_pid.b_2022_pn_bpp_20260624212947.pdf
Berhasil: putusan_317_pid (1).b_2022_pn_bpp_20260624213009.pdf
Berhasil: putusan_317_pid.b_2022_pn_bpp_20260624213009.pdf
Berhasil: putusan_370_pid (1).b_2022_pn_bpp_20260624213044.pdf
Berhasil: putusan_370_pid.b_2022_pn_bpp_20260624213044.pdf
Berhasil: putusan_371_pid.b_2022_pn_bpp_20260624213126.pdf
Berhasil: putusan_20_pid (1).b_2022_pn_bpp_20260624213156.pdf
Berhasil: putusan_20_pid.b_2022_pn_bpp_20260624213156.pdf
Berhasil: putusan_499_pid.b_2021_pn_bpp_20260624213313.pdf
Berhasil: putusan_530_pid (1).b_2021_pn_bpp_20260624213349.pdf
Berhasil: putusan_530_pid.b_2021_pn_bpp_20260624213349.pdf
Berhasil: putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf
Berhasil: putusan_80_pid.b_2021_pn_bpp_20260624213521.pdf
Berhasil: putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf
Jumlah dokumen: 44

In [12]:
import pandas as pd

df = pd.DataFrame(cases)

df.head()

,filename,text
0,putusan_65_pid (1).b_2026_pn_bpp_2026062310032...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
1,putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
2,putusan_66_pid (1).b_2026_pn_bpp_2026062220045...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
3,putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
4,putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...

In [13]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df["clean_text"] = df["text"].apply(clean_text)

In [14]:
df.to_csv(
    "/content/drive/MyDrive/PN BPP/cases.csv",
    index=False
)

In [15]:
import pandas as pd

df = pd.DataFrame(cases)

print(df.shape)
df.head()

(44, 2)

,filename,text
0,putusan_65_pid (1).b_2026_pn_bpp_2026062310032...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
1,putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
2,putusan_66_pid (1).b_2026_pn_bpp_2026062220045...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
3,putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...
4,putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...

In [16]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\n+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    return text.strip()

df["clean_text"] = df["text"].apply(clean_text)

In [17]:
def extract_case_number(filename):
    match = re.search(r'putusan_(.*?)_pn_bpp', filename)
    if match:
        return match.group(1)
    return None

df["case_number"] = df["filename"].apply(extract_case_number)

In [18]:
df["word_count"] = df["clean_text"].apply(
    lambda x: len(x.split())
)

In [19]:
df.to_csv(
    "/content/drive/MyDrive/PN BPP/cases.csv",
    index=False
)

print("CSV berhasil disimpan")

CSV berhasil disimpan

In [20]:
df[["filename","case_number","word_count"]].head()

,filename,case_number,word_count
0,putusan_65_pid (1).b_2026_pn_bpp_2026062310032...,65_pid (1).b_2026,14423
1,putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf,65_pid.b_2026,14423
2,putusan_66_pid (1).b_2026_pn_bpp_2026062220045...,66_pid (1).b_2026,14216
3,putusan_66_pid.b_2026_pn_bpp_20260622200457.pdf,66_pid.b_2026,14216
4,putusan_493_pid.b_2025_pn_bpp_20260624212216.pdf,493_pid.b_2025,13616

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words=None,
    max_features=5000
)

tfidf_matrix = vectorizer.fit_transform(df["clean_text"])

print("Shape TF-IDF:", tfidf_matrix.shape)

Shape TF-IDF: (44, 5000)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

print(similarity_matrix.shape)

(44, 44)

In [23]:
def retrieve(query, k=5):

    query_clean = clean_text(query)

    query_vector = vectorizer.transform([query_clean])

    similarities = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    top_indices = similarities.argsort()[-k:][::-1]

    results = []

    for idx in top_indices:
        results.append({
            "case_number": df.iloc[idx]["case_number"],
            "filename": df.iloc[idx]["filename"],
            "similarity": similarities[idx]
        })

    return pd.DataFrame(results)

In [24]:
retrieve(
    "terdakwa melakukan tindak pidana perjudian online",
    k=5
)

,case_number,filename,similarity
0,641_pid.b_2022,putusan_641_pid.b_2022_pn_bpp_20260624212733.pdf,0.195171
1,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.193668
2,650_pid.b_2022,putusan_650_pid.b_2022_pn_bpp_20260624212656.pdf,0.184439
3,20_pid.b_2022,putusan_20_pid.b_2022_pn_bpp_20260624213156.pdf,0.181596
4,20_pid (1).b_2022,putusan_20_pid (1).b_2022_pn_bpp_2026062421315...,0.181596

In [25]:
hasil = retrieve(
    "penyalahgunaan narkotika jenis sabu",
    k=5
)

hasil.to_csv(
    "/content/drive/MyDrive/PN BPP/retrieval_result.csv",
    index=False
)

hasil

,case_number,filename,similarity
0,272_pid.b_2023,putusan_272_pid.b_2023_pn_bpp_20260624212529.pdf,0.009805
1,80_pid.b_2021,putusan_80_pid.b_2021_pn_bpp_20260624213521.pdf,0.008730
2,499_pid.b_2021,putusan_499_pid.b_2021_pn_bpp_20260624213313.pdf,0.007443
3,569_pid (1).b_2022,putusan_569_pid (1).b_2022_pn_bpp_202606242127...,0.005266
4,569_pid.b_2022,putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf,0.005266

In [26]:
print(df["text"].iloc[0][:5000])

Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 65/Pid.B/2026/PN Bpp
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA

           Pengadilan Negeri Balikpapan yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Para Terdakwa :
Terdakwa I
Nama Terdakwa : SYAFRI SALAM Bin ABD SALAM TUJU (Alm)
Nomor Identitas : 6471050505750028
Tempat lahir : Gowa
Umur/tanggal lahir : 50 Tahun / 05 Mei 1975
Jenis kelamin : Laki-laki
Kebangsaan : Indonesia
Tempat tinggal : Jalan Tondano (Griya Permata Asri) Nomor 146 Rt.
43  Kelurahan  Gunung  Bahagia  Kecamatan
Balikpapan  Selatan  Kota  Balikpapan  Provinsi
Kalimantan Timur
Jalan Serindit III No 76 Kelurahan Gunung Bahagia
Kecamatan Balikpapan Selatan.(Alamat Sekarang)
Agama : Islam
Pekerjaan : Pedagang
Pendidikan : SMP (Tidak tamat)
Terdakwa II
Nama Terdakwa : JAMALUDDIN Bin MAPELAWA (Alm)
Nomor Identitas : 6471050301800004
Tempat lahir : BT MIMBELO
Umur/tanggal lahir : 46 Tahun / 13 Januari 1980
Jenis kelamin : Laki-laki
Kebangsaan : Indonesia
Tempat tinggal : Jalan Syarifuddin Yoes Rt 040 Kelurahan Gunung
Bahagia Kecamatan Balikpapan Selatan
Agama : Islam
Pekerjaan : Wiraswasta
Pendidikan : Tidak Sekolah
Terdakwa III
Nama Terdakwa : SYAMSUL ARIF Bin M. SALEH
Nomor Identitas : 6471051201880006
Tempat lahir : Pandai
Umur/tanggal lahir : 38 Tahun / 12 Januari 1988
Halaman 1 dari 33 Putusan Nomor 66/Pid.B/2026/PN Bpp
          Pid.I.A.3
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan keterkinian informasi yang kami sajikan, hal mana akan terus kami perbaiki dari waktu kewaktu.
Dalam hal Anda menemukan inakurasi informasi yang termuat pada situs ini atau informasi yang seharusnya ada, namun belum tersedia, maka harap segera hubungi Kepaniteraan Mahkamah Agung RI melalui :
Email : kepaniteraan@mahkamahagung.go.id    Telp : 021-384 3348 (ext.318) Halaman 1 Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Mahkamah Agung Republik Indonesia
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Jenis kelamin : Laki-laki
Kebangsaan : Indonesia
Tempat tinggal : Jalan Marsma R Iswahyudi Nomor 9 Rt. 09
Kelurahan Sepinggan Raya Kecamatan Balikpapan
Selatan Kota Balikpapan Provinsi Kalimantan Timur
Agama : Islam
Pekerjaan : Karyawan Swasta
Pendidikan : SMA

        Para Terdakwa ditahan dalam tahanan Rutan oleh :
1. Penyidik sejak tanggal 12 Des ember  2025 s ampai dengan tanggal  31
Desember 2025;
2. Penyidik perpanjangan Penuntut Umum sejak tanggal 01 Januari  2026
sampai dengan tanggal 09 Februari 2026;
3. Penuntut Umum sejak tanggal 28 Januari  2026 sampai dengan tanggal
16 Februari 2026;
4. Hakim  pengadilan  negeri  sejak  tanggal  13  Februari 2026  sampai
dengan tanggal  14 Maret 2025;
5. Perpanjangan penahanan oleh ketua pengadilan negeri sejak tanggal
15 Maret 2026 sampai dengan tanggal 13 Mei 2026;
             Para Terdakwa  mewnghadapi sendiri persidangan;
Pengadilan Negeri tersebut;
Setelah membaca:
- Penetapan   Ketua  Pengadilan  Negeri  Balikpapan Nomor
65/Pid.B/2026/PN Bpp tanggal 1 3 Februari 2026 tentang penunjukan Majelis
Hakim;
- Penetapan  Majelis  Hakim Nomor  65/Pid.B/2026/PN  Bpp tanggal
13 Februari 2026 tentang penetapan hari sidang;
- Berkas perkara dan surat-surat lain yang bersangkutan;
Setelah mendengar keterangan Saksi-saksi dan Para Terdakwa  serta
memperhatikan bukti surat dan barang bukti yang diajukan di persidangan;
Setelah  mendengar  pembacaan  tuntutan  pidana  yang  diajukan  oleh
Penuntut Umum yang pada pokoknya sebagai berikut:
1. Menyatakan  terdakwa  I  Syafri  Salam  Bin  Abd  Salam  Tuju  (Alm),
terdakwa II Jamaluddin Bin Mapelawa (Alm) dan terdakwa III Syamsul Arif
Bin M. Saleh telah terbukti secara sah dan meyakinkan bersalah melakukan
tindak  pidana  “Turut  serta  melakukan  tindak  pidana  yang  menggunakan
kesempatan  main  judi  yang  diadakan  tanpa  izin”  melanggar  Pasal  427
Halaman 2 dari 33 Putusan Nomor 66/Pid.B/2026/PN Bpp
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000
)

tfidf_matrix = vectorizer.fit_transform(df["clean_text"])

print(tfidf_matrix.shape)

(44, 5000)

In [28]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

def retrieve(query, k=5):

    query = clean_text(query)

    query_vector = vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    top_indices = similarities.argsort()[-k:][::-1]

    return pd.DataFrame({
        "case_number": df.iloc[top_indices]["case_number"].values,
        "filename": df.iloc[top_indices]["filename"].values,
        "similarity": similarities[top_indices]
    })

In [29]:
retrieve(
    "terdakwa melakukan perjudian togel",
    k=5
)

,case_number,filename,similarity
0,133_pid.b_2021,putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf,0.304115
1,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.298757
2,2_pid.b_2021,putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf,0.294853
3,569_pid.b_2022,putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf,0.284477
4,569_pid (1).b_2022,putusan_569_pid (1).b_2022_pn_bpp_202606242127...,0.284477

In [30]:
retrieve(
    "memberikan kesempatan kepada masyarakat untuk bermain judi togel",
    k=5
)

,case_number,filename,similarity
0,530_pid.b_2021,putusan_530_pid.b_2021_pn_bpp_20260624213349.pdf,0.227795
1,530_pid (1).b_2021,putusan_530_pid (1).b_2021_pn_bpp_202606242133...,0.227795
2,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.227076
3,371_pid.b_2022,putusan_371_pid.b_2022_pn_bpp_20260624213126.pdf,0.211277
4,133_pid.b_2021,putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf,0.203569

In [31]:
retrieve(
    "menjual nomor togel dan menerima pemasangan angka",
    k=5
)

,case_number,filename,similarity
0,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.234984
1,371_pid.b_2022,putusan_371_pid.b_2022_pn_bpp_20260624213126.pdf,0.203422
2,133_pid.b_2021,putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf,0.203404
3,530_pid (1).b_2021,putusan_530_pid (1).b_2021_pn_bpp_202606242133...,0.179717
4,530_pid.b_2021,putusan_530_pid.b_2021_pn_bpp_20260624213349.pdf,0.179717

In [32]:
print(tfidf_matrix.shape)

(44, 5000)

In [33]:
retrieve("terdakwa melakukan perjudian togel")

,case_number,filename,similarity
0,133_pid.b_2021,putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf,0.304115
1,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.298757
2,2_pid.b_2021,putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf,0.294853
3,569_pid.b_2022,putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf,0.284477
4,569_pid (1).b_2022,putusan_569_pid (1).b_2022_pn_bpp_202606242127...,0.284477

In [34]:
import re

def extract_verdict(text):

    pattern = r"mengadili(.*?)(?:demikian diputuskan|$)"

    match = re.search(
        pattern,
        text.lower(),
        re.DOTALL
    )

    if match:
        return match.group(1)[:1500]

    return ""

df["verdict"] = df["text"].apply(extract_verdict)

In [35]:
def predict_outcome(query):

    result = retrieve(query, k=5)

    best_case = result.iloc[0]

    idx = df[
        df["case_number"] ==
        best_case["case_number"]
    ].index[0]

    return df.loc[idx, "verdict"]

In [36]:
query = """
terdakwa melakukan perjudian togel
"""

print(
    predict_outcome(query)
)

 perkara  pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara terdakwa :
1. nama lengkap : alimin dahlan als. alimin bin dahlan;
2. tempat lahir : sengkang (sul-sel);
3. umur/tanggal lahir : 48 tahun/22 oktober 1973;
4. jenis kelamin : laki-laki;
5. kebangsaan : indonesia;
6. tempat tinggal : jl. letjend. suprapto rt.19 no.93 kel. marga sari,
                                       kec. balikpapan barat kota balikpapan;
7. agama : islam;
8. pekerjaan : wiraswasta;
terdakwa alimin dahlan als. alimin bin dahlan ditahan dalam tahanan rutan
oleh:
1. penyidik sejak tanggal 08 januari 2021 sampai dengan tanggal 27 januari 2021;
2. penyidik perpanjangan oleh pu sejak tanggal 28 januari 2021 sampai dengan
tanggal 08 maret 2021;
3. penyidik perpanjangan pertama oleh ketua pn sejak tanggal 09 maret 2021
sampai dengan tanggal 07 april 2021;
4. penuntut sejak tanggal 18 maret 2021 sampai dengan tanggal 06 april 2021;
5. hakim pn sejak tanggal 30 maret 2021 sampai dengan tanggal 28 april 2021;
6. hakim pn perpanjangan pertama oleh ketua pn sejak tanggal 29 april 2021
sampai dengan tanggal 27 juni 2021;
terdakwa menghadap sendiri;
pengadilan negeri tersebut;
setelah membaca:
- penetapan  ketua pengadilan negeri  balikpapan nomor  133/pid.b/2021/pn
bpp tanggal 30 maret 2021 tentang penunjukan majelis hakim;
halaman 1 dari 14 putusan nomor 133/pid.b/2021/pn bpp
          pid.i.a.3
disclaimer
kepaniteraan mahkamah agung

In [37]:
print(df["case_number"].nunique())

44

In [38]:
import re

def extract_defendant(text):
    match = re.search(
        r'Nama lengkap\s*:\s*(.*?)(?:\n|Tempat lahir)',
        text,
        re.IGNORECASE | re.DOTALL
    )

    if match:
        return match.group(1).strip()

    return ""

df["terdakwa"] = df["text"].apply(extract_defendant)

In [39]:
def extract_nomor_putusan(text):

    match = re.search(
        r'Nomor\s+(\d+/Pid\.B/\d+/PN\s+\w+)',
        text,
        re.IGNORECASE
    )

    if match:
        return match.group(1)

    return ""

df["nomor_putusan"] = df["text"].apply(
    extract_nomor_putusan
)

In [40]:
def extract_pasal(text):

    text = text.lower()

    if "303 bis" in text:
        return "303 bis KUHP"

    if "pasal 303" in text:
        return "303 KUHP"

    return "Tidak ditemukan"

df["pasal"] = df["text"].apply(extract_pasal)

In [41]:
df.to_csv(
    "/content/drive/MyDrive/PN BPP/cases_final.csv",
    index=False
)

In [42]:
df[
    [
        "case_number",
        "terdakwa",
        "pasal",
        "word_count"
    ]
].head()

,case_number,terdakwa,pasal,word_count
0,65_pid (1).b_2026,,Tidak ditemukan,14423
1,65_pid.b_2026,,Tidak ditemukan,14423
2,66_pid (1).b_2026,SULISTYONO Bin (Alm) RUSLAN,Tidak ditemukan,14216
3,66_pid.b_2026,SULISTYONO Bin (Alm) RUSLAN,Tidak ditemukan,14216
4,493_pid.b_2025,WINDY LESTARI BINTI SURIYANSYAH,303 bis KUHP,13616

In [43]:
df.to_csv(
    "/content/drive/MyDrive/PN BPP/PN BPP_final.csv",
    index=False
)

In [44]:
hasil = retrieve(
    "terdakwa melakukan perjudian togel",
    k=5
)

hasil.to_csv(
    "/content/drive/MyDrive/PN BPP/retrieval_result.csv",
    index=False
)

hasil

,case_number,filename,similarity
0,133_pid.b_2021,putusan_133_pid.b_2021_pn_bpp_20260624213453.pdf,0.304115
1,724_pid.b_2022,putusan_724_pid.b_2022_pn_bpp_20260624212641.pdf,0.298757
2,2_pid.b_2021,putusan_2_pid.b_2021_pn_bpp_20260624213557.pdf,0.294853
3,569_pid.b_2022,putusan_569_pid.b_2022_pn_bpp_20260624212745.pdf,0.284477
4,569_pid (1).b_2022,putusan_569_pid (1).b_2022_pn_bpp_202606242127...,0.284477

In [45]:
query = "terdakwa melakukan perjudian togel"

prediksi = predict_outcome(query)

prediction_df = pd.DataFrame({
    "query":[query],
    "predicted_solution":[prediksi]
})

prediction_df.to_csv(
    "/content/drive/MyDrive/PN BPP/predictions.csv",
    index=False
)

prediction_df

,query,predicted_solution
0,terdakwa melakukan perjudian togel,perkara pidana dengan\nacara pemeriksaan bia...

In [46]:
df.columns

Index(['filename', 'text', 'clean_text', 'case_number', 'word_count',
       'verdict', 'terdakwa', 'nomor_putusan', 'pasal'],
      dtype='object')

In [47]:
df.head(3)

,filename,text,clean_text,case_number,word_count,verdict,terdakwa,nomor_putusan,pasal
0,putusan_65_pid (1).b_2026_pn_bpp_2026062310032...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...,mahkamah agung republik indonesia mahkamah agu...,65_pid (1).b_2026,14423,perkara pidana dengan\nacara pemeriksaan bias...,,65/Pid.B/2026/PN Bpp,Tidak ditemukan
1,putusan_65_pid.b_2026_pn_bpp_20260623100320.pdf,Mahkamah Agung Republik Indonesia\nMahkamah Ag...,mahkamah agung republik indonesia mahkamah agu...,65_pid.b_2026,14423,perkara pidana dengan\nacara pemeriksaan bias...,,65/Pid.B/2026/PN Bpp,Tidak ditemukan
2,putusan_66_pid (1).b_2026_pn_bpp_2026062220045...,Mahkamah Agung Republik Indonesia\nMahkamah Ag...,mahkamah agung republik indonesia mahkamah agu...,66_pid (1).b_2026,14216,perkara pidana dengan\nacara pemeriksaan bia...,SULISTYONO Bin (Alm) RUSLAN,66/Pid.B/2026/PN Bpp,Tidak ditemukan